### ISSUE TITLE
Mocking framework

### ISSUE THREAD

**Issue by oleksiyp** [sazzer/tcg#1]
Hi,

hope find you well with this cold call.

I am an author of [mocking framework for Kotlin](http://mockk.io)

I see you are using mockito-kotlin.

I just want you to be aware that there is solution that fully supports Kotlin and ask to try it in your new/current projects.

I can help you if you answer to this issue.

Thanks and please star [it](https://github.com/oleksiyp/mockk)

**Comment by sazzer** [comment]
It looks interesting, but I'm concerned about the need for a Java agent to
use it. I'll certainly have a look on my next kotlin project though.

**Comment by oleksiyp** [comment]
It's optional. For old JVMs

**Comment by sazzer** [comment]
So I can use all of the features and not need an agent, on Java 8 JVM? Good
to know. :-)
